project:
  type: website

website:
  title: "My Fish-Bone"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: About
        href: about.qmd
      - text: Essay on Shinylive/Shiny Apps
        href: shiny-live.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
execute: 
  freeze: auto
  