project:
  type: website

website:
  title: "My Fish-Bone"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: About
        href: about.qmd
      - text: Resume
        href: my-resume.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual
execute: 
  freeze: auto
  